### ISSUE TITLE
Build error in Slicer Preview Release

### ISSUE THREAD

**Issue by lassoan** [jmhuie/Slicer-SegmentGeometry#1]
The extension fails to build in latest Slicer Preview Release due to a missing folder:

```
CMake Error at CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source "FunctionalHomodonty" which is not an
  existing directory.
```

https://slicer.cdash.org/build/2636752/configure

**Comment by jmhuie** [comment]
Thanks for the heads up. I prematurely pushed a change to the CMake file. It should work for the next build.

**Comment by lassoan** [comment]
Awesome, thank you!
